### ISSUE TITLE
[Bug] 使用环境变量配置的 Azure 服务鉴权异常

### ISSUE THREAD

**Issue by Hk-Gosuto** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#198]
#197

**Comment by yuchanns** [comment]
If I don't use any environment and only configure it through the interface, it also won't work.

**Comment by Hk-Gosuto** [comment]
使用以下环境变量配置，自定义模型名使用 Azure 部署名：
```
AZURE_URL=https://xxxx.openai.azure.com/openai/deployments
AZURE_API_KEY=xxxxxxxxxxxxxxx
AZURE_API_VERSION=2024-02-15-preview
```

页面上配置参考上面的环境变量配置也可以正常使用。

**Comment by yuchanns** [comment]
This issue persists.

The issue with using only environment variables for configuration has been resolved. 

However, the same error will occur when configuring solely through the interface without using any environment variables. Just so you know, this situation arises only when environment variables and interface configurations are not used together.

In comparison, there is no problem if they are used in conjunction.

IMO this is caused by the different ways to read the key for the token in two scene.

**Comment by Hk-Gosuto** [comment]
> This issue persists.
> 
> The issue with using only environment variables for configuration has been resolved.
> 
> However, the same error will occur when configuring solely through the interface without using any environment variables. Just so you know, this situation arises only when environment variables and interface configurations are not used together.
> 
> In comparison, there is no problem if they are used in conjunction.
> 
> IMO this is caused by the different ways to read the key for the token in two scenes.
> 
> Please reopen it @Hk-Gosuto

Are you referring to this error?

```json
{"error":true,"msg":"empty access code"}
```

**Comment by yuchanns** [comment]
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/25029451/6ba80626-7ebf-4b15-a64a-d3edf0ac860a)

![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/25029451/f0470426-13cc-4449-ad91-465402b6efdf)


No, just the same error `{"error":"OpenAI or Azure OpenAI API key not found"}`

**Comment by yuchanns** [comment]
Works now. Thank you!
