### ISSUE TITLE
[Feature] How to easily add other open source models like Falcon or LLaMa 2 as one of the options.

### ISSUE THREAD

**Issue by crypticatul** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#54]
**Is your feature request related to a problem? Please describe.**
Yes, OpenAI will be too costly for a generic use case. Also, privacy takes a hit.

**Describe the solution you'd like**
Either an economical API for Falcon180B or LLaMa2 70B integrated with this app. 

**Describe alternatives you've considered**
An API for Falcon180B or LLaMa2 70B or self-hosted on some cloud.
I have startup credits on AWS and Azure. What will be the best way for me to integrate LLaMa 2 or Falcon to ChatGPT Next as one of the options with GPT 3.5-Turbo and GPT-4?

**Additional context**
Please suggest step-by-step instructions to do this as I am quite a newbie in this.

**Comment by Hk-Gosuto** [comment]
The core of this project is based on OpenAI's Function calling feature, for more details please refer to: https://openai.com/blog/function-calling-and-other-api-updates
If you want to replace this part of the functionality with an open-source model, you can follow these steps:
1. You need a fine-tuned version of the model that supports function calling, such as: https://huggingface.co/Trelis/Llama-2-7b-chat-hf-function-calling-v2
2. Make sure the API interface is consistent with OpenAI's interface, refer to: https://platform.openai.com/docs/api-reference/chat/create?lang=curl
3. Use the new model endpoint instead of OpenAI's endpoint.
4. If you don't want to modify the program code, keep the model name in the API interface as `gpt-3.5-turbo`.
